title: "YTC"
email: myarachma92@gmail.com
timezone: UTC
baseurl: "https://yusuftutorial.xyz"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: yusuf
paginate: 30
disqus: 'masterwifinetworksolution'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  highlighter: rouge
#    input: GFM
  syntax_highlighter_opts:
    disable: false
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  yusuf:
    name: Muhammad Yusuf
    display_name: Muhammad Yusuf
    avatar: 'assets/images/yusuf.png'
    email: myarachma92@@gmail.com
    web: https://github.com/yusuftutorial
    youtube: https://youtube.com/@yusuftutorialchannel
    description: "Jika anda mengagumi hasil karya saya, anda bisa support saya."

# Social
social:
  telegram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/profile.php?id=61559143289111
  youtube: https://www.youtube.com/channel/UClbAMHpHxjdBJMLSDqr93xw

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives